# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  run-python-test:
   runs-on: ubuntu-latest
   
   steps:
  
   - name: Checkout
     uses: actions/checkout@v2.3.4
  
   - name: Setup Python
     uses: actions/setup-python@v2.2.2
     with:
      python-version: 3.8
  
   - name: Execute Test Script
     env: # Or as an environment variable
       super_secret: ${{ secrets.YANDEX_TOKEN}}
     run: |
      echo "Store: ${{ secrets.YANDEX_TOKEN }}"
      # API_YANDEX_KEY=${{ secrets.YANDEX_TOKEN }}
      python3 main.py
